version: "3.8"
services:
  api:    
    container_name: "docker-fastapi-websocket"
    build:  .
    command: uvicorn app.main:app --reload --host 0.0.0.0 
    ports:
     - 8080:8000
    volumes:
      - #nil